import { ClothingProductData } from '@/types/shared/product';

export const SAMPLE_CLOTHING: ClothingProductData = {
  id: 'prod_01HZY8K3N9QW2X7VBTG4M5R6E1',
  name: 'Shadow Stripe Jersey',
  slug: 'shadow-stripe-jersey',
  brand: {
    id: 'brand_ashluxe',
    name: 'Ashluxe',
    slug: 'ashluxe',
  },
  category: {
    id: 'cat_tshirts',
    name: 'T-Shirts',
    slug: 't-shirts',
  },
  collections: [
    {
      id: 'col_ss26_drop1',
      name: 'SS26 Drop 1',
      slug: 'ss26-drop-1',
    },
    {
      id: 'col_core_essentials',
      name: 'Core Essentials',
      slug: 'core-essentials',
    },
  ],
  productType: 'apparel',
  gender: 'Unisex',
  colors: [
    {
      id: '1',
      name: 'Black',
      hexCode: '#1c1c1c',
      swatchImage: null,
    },
    {
      id: '2',
      name: 'Shadow Stripe Blue',
      hexCode: '#2b3a4a',
      swatchImage: null,
    },
  ],
  description: {
    narrative:
      'Inspired by the interplay of light and shadow across city skylines at dusk, the Shadow Stripe Jersey blends heavyweight comfort with a subtle tonal stripe motif. Designed for movement, built for the everyday uniform.',
    styleCode: 'DRP26-SSJ-01',
    fitType: 'Oversized Fit',
    fabricComposition: '450gsm Heavyweight 100% Organic Cotton',
    careInstructions: [
      'Machine wash cold',
      'Hang dry recommended',
      'Do not iron print',
      'Do not tumble dry',
    ],
    releaseDate: '2026-02-14T00:00:00.000Z',

    editorialHighlights: [
      'Custom molded hardware',
      'Distressed ribbing',
      'Tonal jacquard stripe knit',
    ],
    additionalSections: [
      {
        title: 'Size & Fit Guide',
        content:
          'This piece is designed with an oversized fit. For a true-to-size look, order your regular size. For an extra relaxed silhouette, size up.',
      },
      {
        title: 'Shipping & Returns',
        content:
          'Free standard shipping on all orders. Returns accepted within 14 days of delivery in original condition with tags attached.',
      },
    ],
  },
  features: [
    'Heavyweight jersey construction',
    'Ribbed crewneck collar',
    'Reinforced shoulder seams',
    'Tonal woven label',
  ],
  media: [
    {
      url: 'https://sfycdn.speedsize.com/f872e742-7b4a-4913-b7dc-4d0ce34f2142/ash-luxe.com/cdn/shop/files/Ashluxe_Shadow_Stripe_Jersey_Black.png?v=1786101587&width=1200',
      alt: 'Model wearing front view of black jersey',
      type: 'image',
      order: 0,
      colorId: '1',
    },
    {
      url: 'https://sfycdn.speedsize.com/f872e742-7b4a-4913-b7dc-4d0ce34f2142/ash-luxe.com/cdn/shop/files/Ashluxe_Celebration_Bowling_Shirt_Off-white.png?v=1786101761&width=1200',
      alt: 'Model wearing side view of black jersey',
      type: 'image',
      order: 1,
      colorId: '1',
    },
    {
      url: 'https://sfycdn.speedsize.com/f872e742-7b4a-4913-b7dc-4d0ce34f2142/ash-luxe.com/cdn/shop/files/Ashluxe_Celebration_Bowling_Shirt_Off-white.png?v=1786101761&width=1200',
      alt: 'Model wearing back view of black jersey',
      type: 'image',
      order: 2,
      colorId: '1',
    },
    {
      url: 'https://sfycdn.speedsize.com/f872e742-7b4a-4913-b7dc-4d0ce34f2142/ash-luxe.com/cdn/shop/files/Ashluxe_Celebration_Bowling_Shirt_Off-white.png?v=1786101761&width=1200',
      alt: 'Close-up detail of black jersey fabric',
      type: 'image',
      order: 3,
      colorId: '1',
    },
    {
      url: 'https://sfycdn.speedsize.com/f872e742-7b4a-4913-b7dc-4d0ce34f2142/ash-luxe.com/cdn/shop/files/AshluxeShadowStripeJerseyBlue.png?v=1786099543&width=1800',
      alt: 'Model wearing front view of shadow stripe jersey',
      type: 'image',
      order: 0,
      colorId: '2',
    },
    {
      url: 'https://sfycdn.speedsize.com/f872e742-7b4a-4913-b7dc-4d0ce34f2142/ash-luxe.com/cdn/shop/files/AshluxeInfernoNoirDressBlack.png?v=1776789417&width=1500',
      alt: 'Lifestyle shot on model',
      type: 'image',
      order: 0,
    },
  ],
  variants: [
    {
      id: 'var_blk_s',
      colorId: '1',
      sizeId: 'size_s',
      size: 'S',
      sku: 'ASH-SSJ-BLK-S',
      barcode: '0194732105512',
      stockQuantity: 0,
      reservedQuantity: 2,
      availableQuantity: 0,
      reorderLevel: 5,
      active: true,
      priceOverride: null,
    },
    {
      id: 'var_blk_m',
      colorId: '1',
      sizeId: 'size_m',
      size: 'M',
      sku: 'ASH-SSJ-BLK-M',
      barcode: '0194732105529',
      stockQuantity: 30,
      reservedQuantity: 4,
      availableQuantity: 26,
      reorderLevel: 5,
      active: true,
      priceOverride: null,
    },
    {
      id: 'var_blk_l',
      colorId: '1',
      sizeId: 'size_l',
      size: 'L',
      sku: 'ASH-SSJ-BLK-L',
      barcode: '0194732105536',
      stockQuantity: 18,
      reservedQuantity: 1,
      availableQuantity: 17,
      reorderLevel: 5,
      active: true,
      priceOverride: null,
    },
    {
      id: 'var_blk_xl',
      colorId: '1',
      sizeId: 'size_xl',
      size: 'XL',
      sku: 'ASH-SSJ-BLK-XL',
      barcode: '0194732105543',
      stockQuantity: 10,
      reservedQuantity: 0,
      availableQuantity: 10,
      reorderLevel: 5,
      active: true,
      priceOverride: 5000,
    },
    {
      id: 'var_blue_s',
      colorId: '2',
      sizeId: 'size_s',
      size: 'S',
      sku: 'ASH-SSJ-BLU-S',
      barcode: '0194732105550',
      stockQuantity: 15,
      reservedQuantity: 0,
      availableQuantity: 15,
      reorderLevel: 5,
      active: true,
      priceOverride: null,
    },
    {
      id: 'var_blue_m',
      colorId: '2',
      sizeId: 'size_m',
      size: 'M',
      sku: 'ASH-SSJ-BLU-M',
      barcode: '0194732105567',
      stockQuantity: 20,
      reservedQuantity: 3,
      availableQuantity: 17,
      reorderLevel: 5,
      active: true,
      priceOverride: null,
    },
    {
      id: 'var_blue_l',
      colorId: '2',
      sizeId: 'size_l',
      size: 'L',
      sku: 'ASH-SSJ-BLU-L',
      barcode: '0194732105574',
      stockQuantity: 0,
      reservedQuantity: 0,
      availableQuantity: 0,
      reorderLevel: 5,
      active: false,
      priceOverride: null,
    },
  ],
  pricing: {
    currency: 'NGN',
    basePrice: 85000,
    compareAtPrice: 110000,
    costPrice: 32000,
  },
  seo: {
    title: 'Shadow Stripe Jersey | Ashluxe',
    description:
      'Shop the Shadow Stripe Jersey from Ashluxe — heavyweight organic cotton with a tonal stripe knit, oversized fit. Free shipping.',
    keywords: ['ashluxe', 'jersey', 'streetwear', 'oversized tee', 'shadow stripe'],
  },
  tags: ['new-arrival', 'unisex', 'heavyweight', 'ss26'],
  active: true,
  publishedAt: '2026-02-14T09:00:00.000Z',
  createdAt: '2026-01-20T11:32:00.000Z',
  updatedAt: '2026-08-10T16:45:00.000Z',
};
