import type { Metadata } from 'next';
import {
  Geist,
  Geist_Mono,
  Macondo,
  Archivo,
  Archivo_Black,
  IBM_Plex_Mono,
} from 'next/font/google';
import './globals.css';
import { RootLayout as Layout } from '../components/layouts/root-layout';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const macondo = Macondo({
  variable: '--font-macondo',
  weight: '400',
  subsets: ['latin'],
});

const archivo = Archivo({
  variable: '--font-archivo',
  weight: '400',
  subsets: ['latin'],
});

const archivo_black = Archivo_Black({
  variable: '--font-archivo-black',
  weight: '400',
  subsets: ['latin'],
});

const ibm_plex_mono = IBM_Plex_Mono({
  variable: '--font-ibm-plex-mono',
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${macondo.variable} ${archivo.variable} ${archivo_black.variable} ${ibm_plex_mono.variable} h-full antialiased`}
    >
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
