import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { RootLayout as Layout } from '../components/layouts/root-layout';

// 1. Geist Sans (Variable)
const geistSans = localFont({
  src: '../node_modules/@fontsource-variable/geist/files/geist-latin-wght-normal.woff2',
  variable: '--font-geist-sans',
});

// 2. Geist Mono (Variable)
const geistMono = localFont({
  src: '../node_modules/@fontsource-variable/geist-mono/files/geist-mono-latin-wght-normal.woff2',
  variable: '--font-geist-mono',
});

// 3. Macondo (Static 400)
const macondo = localFont({
  src: '../node_modules/@fontsource/macondo/files/macondo-latin-400-normal.woff2',
  variable: '--font-macondo',
});

// 4. Archivo (Variable)
const archivo = localFont({
  src: '../node_modules/@fontsource-variable/archivo/files/archivo-latin-wght-normal.woff2',
  variable: '--font-archivo',
});

// 5. Archivo Black (Static 400)
const archivo_black = localFont({
  src: '../node_modules/@fontsource/archivo-black/files/archivo-black-latin-400-normal.woff2',
  variable: '--font-archivo-black',
});

// 6. IBM Plex Mono (Static 400)
const ibm_plex_mono = localFont({
  src: '../node_modules/@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-400-normal.woff2',
  variable: '--font-ibm-plex-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Kept your layout properties types intact
export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${macondo.variable} ${archivo.variable} ${archivo_black.variable} ${ibm_plex_mono.variable} h-full antialiased`}
    >
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
